# Generated by Django 3.2 on 2021-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesionario',
            name='Ubicacion',
            field=models.CharField(max_length=60),
        ),
    ]
